### ISSUE TITLE
Doesnt seem to work

### ISSUE THREAD

**Issue by pratima320** [mhadaily/Salesforce1-on-desktop#1]
Hi, I tried following the steps mentioned here but it doesn't seem to work. My org is in Winter18 instance. Any idea why?

**Comment by mhadaily** [comment]
Hi, 
Will test it out and get back to you shortly. maybe Salesforce has changed something and I need to update the addon in order to make it compatible with new change. will let you know soon.

**Comment by pratima320** [comment]
Thank  you!

**Comment by wkaskie** [comment]
I'm having the same issue. Nothing is happening.

**Comment by mhadaily** [comment]
I had already updated but it seems salesforce has changed their URL again, I will update and release a new update shortly today.

**Comment by harmoney-jontie** [comment]
still not working

**Comment by mhadaily** [comment]
I am sorry for inconvenient cause, I have no longer access to salesforce to test this plugin properly, therefore I am not aware of the latest changes in Salesforce to fix the problem. Hence, I have unpublished this extension and will close this repo. 

Thanks,
